name: fep
package: fep
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    cached_network_image: ^3.4.1
    card_swiper: ^3.0.1
    dotted_border: ^2.1.0
    dropdown_search: ^6.0.1
    flex_color_picker: ^3.6.0
    flutter:
        sdk: flutter
    flutter_colorpicker: ^1.1.0
    flutter_dash: ^1.0.0
    flutter_inappwebview: ^6.1.5
    flutter_localization: ^0.2.2
    flutter_svg: ^2.0.10+1
    font_awesome_flutter: ^10.7.0
    get: ^4.6.6
    get_storage: ^2.1.1
    google_fonts: ^6.2.1
    http: ^1.2.2
    infinite_scroll_pagination: ^4.0.0
    liquid_pull_to_refresh: ^3.0.1
    package_info_plus: ^8.0.2
    percent_indicator: ^4.2.3
    syncfusion_flutter_charts: ^27.2.2
    url_launcher: ^6.3.1
    video_player: ^2.9.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/icons/
        - assets/images/
        - assets/modulos/

    fonts:
        - family: Montserrat
          fonts:
              - asset: assets/fonts/Montserrat-Regular.ttf
